

export const all_routes = {
  // MAIN
  dashboard: "/dashboard", // alias for index.html
  chat: "/chat",
  voiceCall: "/voice-call",
  videoCall: "/video-call",
  calendar: "/calendar",
  email: "/email",
  emailCompose: "/email-compose",
  emailDetails: "/email-details",
  contacts: "/contacts",
  contactList: "/contact-list",
  invoice: "/invoice",
  invoiceDetails: "/invoice-details",
  addInvoice:"/add-invoice",
  editInvoice:"/edit-invoice",
  todo: "/todo",
  notes: "/notes",
  kanbanView: "/kanban-view",
  fileManager: "/file-manager",
  socialFeed: "/social-feed",
  searchResult: "/search-result",
  layoutMini: "/layout-mini",
  layoutHoverview: "/layout-hoverview",
  layoutHidden: "/layout-hidden",
  layoutFullwidth: "/layout-fullwidth",
  layoutRtl: "/layout-rtl",
  layoutDark: "/layout-dark",

  // Healthcare
  patients: "/patients",
  editPatient: "/edit-patients",
  allPatientsList: "/all-patients-list",
  patientDetails: "/patient-details",
  patientDetailsAppointment:"/patient-details-appointment",
  patientDetailsVitalSign:"/patient-details-vital-sign",
  patientetailsVisitHistory:"/patient-details-visit-history",
  patientetailsLabResults:"/patient-details-lab-results",
  patientdetailsPrescription:"/patient-details-prescription",
  patientetailsMedicalHistory:"/patient-details-medical-history",
  patientetailsDocuments:"/patient-details-documents",
  appointmentConsultation:"/appointment-consultation",
  patientDetailsVisitHistory:"/patient-details-visit-history",
  patientDetailsLabResults:"/patient-details-lab-results",
  addPatient: "/add-patient",
  doctors: "/doctors",
  allDoctorsList:"/all-doctors-list",
  addDoctors: "/add-doctors",
  editDoctors: "/edit-doctors",
  doctorDetails: "/doctors-details",
  allDoctors: "/all-doctors",
  appointments: "/appointments",
  admissions: "/admissions",
  visits: "/visits",
  startVisits: "/start-visits",
  frontdeskQueue: "/frontdesk-queue",
  nurseQueue: "/nurse-queue",
  doctorQueue: "/doctor-queue",
  labQueue: "/lab-queue",
  pharmacyQueue: "/pharmacy-queue",
  billingQueue: "/billing-queue",
  labResults: "/lab-results",
  medicalResults: "/medical-results",
  pharmacy: "/pharmacy",
  requests: "/requests",
  manageInvoicesDetails:"/manage-invoices-details",
  manageEditInvoices:"/manage-edit-invoices",
  manageAddInvoices:"/manage-add-invoices",
  


  // MANAGE
  staff: "/staffs",
  staffDirectory: "/staff-directory",
  attendance: "/attendance",
  accounting: "/accounting",
  billingDepartment: "/billing-department",
  addBillingRecord: "/add-billing-record",
  editBillingRecord: "/edit-billing-record",
  billingRecordDetails: "/billing-record-details",
  branchManagement: "/branch-management",
  insuranceManagement: "/insurance-management",
  insurancePatientData: "/insurance-patient-data",
  serviceCharges: "/service-charges",
  queueMonitoring: "/queue-monitoring",
  notifications: "/notifications",
  messages: "/messages",
  manageInvoices: "/manage-invoices",
  generalSettings: "/general-settings",
  securitySettings: "/security-settings",
  notificationsSettings: "/notifications-settings",

  // PAGES
  login: "/login",
  signUp: "/sign-up",
  forgotPassword: "/forgot-password",
  changePassword: "/change-password",
  lockScreen: "/lock-screen",
  error404: "/error-404",
  error500: "/error-500",
  starterPage: "/starter-page",
  comingSoon: "/coming-soon",
  underMaintenance: "/under-maintenance",
  privacyPolicy: "/privacy-policy",
  termsAndConditions: "/terms-and-conditions",

  // UI Interface - Base UI
  uiAccordion: "/ui-accordion",
  uiAlerts: "/ui-alerts",
  uiAvatar: "/ui-avatar",
  uiBadges: "/ui-badges",
  uiBreadcrumb: "/ui-breadcrumb",
  uiButtons: "/ui-buttons",
  uiButtonsGroup: "/ui-buttons-group",
  uiCards: "/ui-cards",
  uiCarousel: "/ui-carousel",
  uiCollapse: "/ui-collapse",
  uiDropdowns: "/ui-dropdowns",
  uiRatio: "/ui-ratio",
  uiGrid: "/ui-grid",
  uiImages: "/ui-images",
  uiLinks: "/ui-links",
  uiListGroup: "/ui-list-group",
  uiModals: "/ui-modals",
  uiOffcanvas: "/ui-offcanvas",
  uiPagination: "/ui-pagination",
  uiPlaceholders: "/ui-placeholders",
  uiPopovers: "/ui-popovers",
  uiProgress: "/ui-progress",
  uiScrollspy: "/ui-scrollspy",
  uiSpinner: "/ui-spinner",
  uiNavTabs: "/ui-nav-tabs",
  uiToasts: "/ui-toasts",
  uiTooltips: "/ui-tooltips",
  uiTypography: "/ui-typography",
  uiUtilities: "/ui-utilities",
  themeTest: "/theme-test",

  // UI Interface - Advanced UI
  uiDragula: "/ui-dragula",
  uiClipboard: "/ui-clipboard",
  uiRangeslider: "/ui-rangeslider",
  uiSweetalerts: "/ui-sweetalerts",
  uiLightbox: "/ui-lightbox",
  uiRating: "/ui-rating",
  uiScrollbar: "/ui-scrollbar",

  // UI Interface - Forms
  formBasicInputs: "/form-basic-inputs",
  formCheckboxRadios: "/form-checkbox-radios",
  formInputGroups: "/form-input-groups",
  formGridGutters: "/form-grid-gutters",
  formMask: "/form-mask",
  formFileupload: "/form-fileupload",
  formHorizontal: "/form-horizontal",
  formVertical: "/form-vertical",
  formFloatingLabels: "/form-floating-labels",
  formValidation: "/form-validation",
  formSelect: "/form-select",
  formWizard: "/form-wizard",
  formPickers: "/form-pickers",
  formEditors: "/form-editors",

  // UI Interface - Tables
  tablesBasic: "/tables-basic",
  dataTables: "/data-tables",

  // UI Interface - Charts
  chartApex: "/chart-apex",
  chartC3: "/chart-c3",
  chartMorris: "/chart-morris",
  chartFlot: "/chart-flot",
  chartPeity: "/chart-peity",

  // UI Interface - Icons
  iconFontawesome: "/icon-fontawesome",
  iconTabler: "/icon-tabler",
  iconBootstrap: "/icon-bootstrap",
  iconRemix: "/icon-remix",
  iconFeather: "/icon-feather",
  iconIonic: "/icon-ionic",
  iconMaterial: "/icon-material",
  iconPe7: "/icon-pe7",
  iconSimpleline: "/icon-simpleline",
  iconThemify: "/icon-themify",
  iconWeather: "/icon-weather",
  iconTypicon: "/icon-typicon",
  iconFlag: "/icon-flag",

  // UI Interface - Widgets
  widgets: "/widgets",

  // HELP
  documentation: "#",
  changelog: "#",
  // Multi Level: use '#' for now, or add real paths if needed
};
